### ISSUE TITLE
Collect KafkaTopicSample events for Kubernetes-hosted Kafka clusters

### ISSUE THREAD

**Issue by dipeti** [newrelic/nri-kafka#261]
### Description
I would like to be able to collect events of KafkaTopicSample against my strimzi-managed kafka cluster hosted in Kubernetes. 
As far as I understand the current integration configuration does not allow for collecting KafkaTopicSample events whilst having `LOCAL_ONLY_COLLECTION: true`. 
_"Note that activating this flag will skip KafkaTopicSample collection"_ [docs](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-config/)

Given my kafka brokers are hosted only on select kubernetes worker nodes
- autodiscovery must be enabled to guarantee only those kubelet-agents connect to the broker which are hosted on the same node 
- `LOCAL_ONLY_COLLECTION: true` must be set because, as per the docs, environments that use discovery (such as Kubernetes) must be set to true.

### Acceptance Criteria
Integration configuration should support collecting KafkaTopicSample for Kafka Clusters hosted Kubernetes. 

### Describe Alternatives
The JMX-endpoint exposes these metrics - and my agent can connect to JMX on each broker. Could the events be extracted from the JMX-endpoint?

### Additional context
nri-bundle chart version: 5.0.26
### Estimates
M = 3-5 days (1 week)

### NewRelic Integration Configuration: 
The below configuration collects `KafkaBrokerSample` and `KafkaOffsetSample` but does not collect `KafkaTopicSample`. 
```yaml
  integrations:
    kafka-config:
      discovery:
        command:
          exec: '/var/db/newrelic-infra/nri-discovery-kubernetes --tls --port 10250'
          match:
            label.app.kubernetes.io/name: kafka
      integrations:
        - name: nri-kafka
          env:
            AUTODISCOVER_STRATEGY: bootstrap
            KAFKA_VERSION: "3.4.0"
            BOOTSTRAP_BROKER_HOST: '${discovery.podName}.be-kafka-brokers.${discovery.namespace}.svc.cluster.local'
            BOOTSTRAP_BROKER_JMX_PORT: 9999
            BOOTSTRAP_BROKER_KAFKA_PORT: 9093
            BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
            DEFAULT_JMX_PORT: 9999
            CLUSTER_NAME: "kafka"
            COLLECT_BROKER_TOPIC_DATA: true
            COLLECT_TOPIC_SIZE: true
            COLLECT_TOPIC_OFFSET: true
            LOCAL_ONLY_COLLECTION: true
            TOPIC_MODE: "all"
            CONSUMER_OFFSET: false
          interval: 15s
          labels:
            role: kafka-core
        - name: nri-kafka
          env:
            AUTODISCOVER_STRATEGY: bootstrap
            KAFKA_VERSION: "3.4.0"
            BOOTSTRAP_BROKER_HOST: '${discovery.podName}.be-kafka-brokers.${discovery.namespace}.svc.cluster.local'
            BOOTSTRAP_BROKER_KAFKA_PORT: 9093
            BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
            CLUSTER_NAME: "kafka"
            LOCAL_ONLY_COLLECTION: true
            CONSUMER_OFFSET: true
            CONSUMER_GROUP_REGEX: ".*"
            CONSUMER_GROUP_OFFSET_BY_TOPIC: true
          interval: 30s
          labels:
            role: kafka-consumer-offset


```
