### ISSUE TITLE
Collect offset from all consumer groups (Feature Request)

### ISSUE THREAD

**Issue by wojtek-oledzki** [newrelic/nri-kafka#50]
##### Collect consumer offset from wildcard groups

When collecting stats from Kafka, it would be really useful to be able to collect offset from All consumer groups or be able to use wildcard in consumer_groups name.

In some environments, topics & consumer groups are created frequently which means that the NewRelic dashboards (nri-kafka config) will be always playing catch-up game.

Example config for monitoring all Team's "A" consumer groups created for Team's A topics
```YAML
  - name: kafka-consumer-offsets
    command: consumer_offset
    arguments:
      consumer_groups: '{
        "company.teamA.*" : {"company.teamA.*": []},
        }'
```

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs
