### ISSUE TITLE
2.12.0 release is not backwards compatible with previous configurations.

### ISSUE THREAD

**Issue by rhyas** [newrelic/nri-kafka#81]
##### Description of the problem

The latest release (2.12.0) breaks existing implementations of the agent. 
```
time="2020-04-06T11:38:30-06:00" level=debug msg="Integration command wrote to stderr" instance=kafka-inventory integration=com.newrelic.kafka prefix=config/kafka stderr="[INFO] Runn ing core collection\n[DEBUG] Connected to 10.1.1.34:2181\n[DEBUG] authenticated: id=100526657275891436, timeout=4000\n[DEBUG] re-submitting `0` credentials after reconnect\n[WARN]  Failed creating client: build ssl config: open : no such file or directory\n[WARN] Failed creating client: create SASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PL AINTEXT auth\n[ERR] Failed to get JMX connection info from broker id 200: found no supported endpoint that successfully connected to broker with host \n[WARN] Failed creating client:  build ssl config: open : no such file or directory\n[WARN] Failed creating client: create SASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PLAINTEXT auth\n[ERR] Fai led to get JMX connection info from broker id 201: found no supported endpoint that successfully connected to broker with host \n[WARN] Failed creating client: build ssl config: open  : no such file or directory\n[WARN] Failed creating client: create SASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PLAINTEXT auth\n[ERR] Failed to get JMX connecti on info from broker id 202: found no supported endpoint that successfully connected to broker with host \n[WARN] Failed creating client: build ssl config: open : no such file or dire ctory\n[WARN] Failed creating client: create SASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PLAINTEXT auth\n[ERR] Failed to get JMX connection info from broker id  203: found no supported endpoint that successfully connected to broker with host \n[WARN] Failed creating client: build ssl config: open : no such file or directory\n[WARN] Failed cr eating client: create SASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PLAINTEXT auth\n[ERR] Failed to get JMX connection info from broker id 204: found no supported  endpoint that successfully connected to broker with host \n[WARN] Failed creating client: build ssl config: open : no such file or directory\n[WARN] Failed creating client: create S ASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PLAINTEXT auth\n[ERR] Failed to get JMX connection info from broker id 205: found no supported endpoint that successf ully connected to broker with host \n[WARN] Failed creating client: build ssl config: open : no such file or directory\n[WARN] Failed creating client: create SASL_SSL config: all sas l_gssapi_* arguments must be set for SASL_PLAINTEXT auth\n[ERR] Failed to get JMX connection info from broker id 206: found no supported endpoint that successfully connected to broke r with host \n[WARN] Failed creating client: build ssl config: open : no such file or directory\n[WARN] Failed creating client: create SASL_SSL config: all sasl_gssapi_* arguments mu st be set for SASL_PLAINTEXT auth\n[ERR] Failed to get JMX connection info from broker id 207: found no supported endpoint that successfully connected to broker with host \n[WARN] Fa iled creating client: build ssl config: open : no such file or directory\n[WARN] Failed creating client: create SASL_SSL config: all sasl_gssapi_* arguments must be set for SASL_PLAI NTEXT auth\n[ERR] Failed to get JMX connection info from broker id 208: found no supported endpoint that successfully connected to broker with host \n[ERR] Failed to get a kafka clie nt: cannot create sarama client with no brokers\n" working-dir=/var/db/newrelic-infra/newrelic-integrations
```
I haven't gotten to the bottom of how or why yet, but it is most definitely related to the most recent release. Perhaps there's some missing default configuration file? The error message is *really* unclear, and there's no real pointer as to what's going on, or how to go about fixing it. The changelog doesn't reflect any useful information about the change, or what needs to be changed to be compatible, and there were no documentation changes or updates included with the merge tou outling any new settings. We don't actively uses SASL, but the cluster is configured with both SASL_SSL and SSL, with SSL being the first listener, and the default inter-broker-protocol. I've tried changing various config options and what not, but so far have not been able to get this version of the plugin back into a functional state.

Here is the configuration that *was* working before this agent update:
```
integration_name: com.newrelic.kafka

instances:
  - name: kafka-metrics
    command: metrics
    arguments:
      default_jmx_user: jmx
      default_jmx_password: passwd
      zookeeper_hosts: '[{"host": "10.1.1.34", "port": 2181}]'
      topic_mode: All
      collect_topic_size: false

  - name: kafka-inventory
    command: inventory
    arguments:
      default_jmx_user: jmx
      default_jmx_password: passwd
      zookeeper_hosts: '[{"host": "10.1.1.34", "port": 2181}]'
      topic_mode: All

  - name: kafka-consumer-offsets
    command: consumer_offset
    arguments:
      zookeeper_hosts: '[{"host": "10.1.1.34", "port": 2181}]'
      consumer_group_regex: '.*'
```

I have not found a configuration yet that works with the new agent. 

##### OS

- [ ] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [x] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs
