### ISSUE TITLE
nri-kafka seems to be making an unsupported API Call.

### ISSUE THREAD

**Issue by rhyas** [newrelic/nri-kafka#86]
##### Description of the problem

Kafka logging errors:

[2020-07-20 15:08:42,367] ERROR [KafkaApi-200] Error when handling request: clientId=nri-kafka, correlationId=0, api=DESCRIBE_CONFIGS, version=0, body={resources=[{resource_type=0,resource_name=-1,config_names=null}]} (kafka.server.KafkaApis)
org.apache.kafka.common.errors.InvalidRequestException: Unexpected resource type UNKNOWN for resource -1

Not sure how to resolve, but possibly related to this? https://github.com/confluentinc/confluent-kafka-dotnet/issues/1044

Ubuntu = 16.04 
nri-kafka = 2.13.4-1
Kafka = 2.5.0 (Confluent 5.5.1) (Also happens on Kafka 2.0.0 and Kafka 1.0.0 non confluent versions)

**Comment by camdencheek** [comment]
Hi @rhyas -- Can you try running the integration with `kafka_version: 2.5.0`?

**Comment by rhyas** [comment]
This is Kafka version 2.5.0. It's the Confluent community packaging, which is 5.5.1, but the core is Kafka 2.5.0. https://docs.confluent.io/current/release-notes/index.html

**Comment by camdencheek** [comment]
Sorry, I meant configuring the integration to use the argument `kafka_version: 2.5.0`. The library we use (`sarama`) requires that we specify the Kafka version so that the correct version of each of the API calls can be made.

**Comment by rhyas** [comment]
Oh. Gotcha. Did that, doesn't seem to have changed anything. Can confirm that the agent seems to be picking that setting up though:

time="2020-07-20T17:48:08-06:00" level=info msg="Integration info" arguments="map[default_jmx_user:jmx topic_mode:All bootstrap_broker_host:localhost bootstrap_broker_kafka_port:9093 kafka_version:2.5.0 collect_topic_size:false default_jmx_password:<HIDDEN> bootstrap_broker_jmx_port:9000 tls_insecure_skip_verify:true autodiscover_strategy:bootstrap bootstrap_broker_kafka_protocol:SSL]" command=metrics commandLine="[./bin/nri-kafka --metrics]" env-vars="map[COLLECT_TOPIC_SIZE:false AUTODISCOVER_STRATEGY:bootstrap DEFAULT_JMX_PASSWORD:<HIDDEN> BOOTSTRAP_BROKER_JMX_PORT:9000 TLS_INSECURE_SKIP_VERIFY:true KAFKA_VERSION:2.5.0 BOOTSTRAP_BROKER_HOST:localhost BOOTSTRAP_BROKER_KAFKA_PROTOCOL:SSL TOPIC_MODE:All DEFAULT_JMX_USER:jmx BOOTSTRAP_BROKER_KAFKA_PORT:9093 PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin VERBOSE:0]" instance=kafka-metrics integration=com.newrelic.kafka interval=15 labels="map[env:test role:test-kafka]" os=linux prefix=integration/com.newrelic.kafka protocolVersion=2 workingDir=/var/db/newrelic-infra/newrelic-integrations

Here's the config I'm using:
```
integration_name: com.newrelic.kafka

instances:
  - name: kafka-metrics
    command: metrics
    arguments:
      default_jmx_user: jmx
      default_jmx_password: ***********
      autodiscover_strategy: bootstrap
      bootstrap_broker_host: localhost
      bootstrap_broker_kafka_port: 9093
      bootstrap_broker_kafka_protocol: SSL
      bootstrap_broker_jmx_port: 9000
      tls_insecure_skip_verify: true
      kafka_version: 2.5.0
      topic_mode: All
      collect_topic_size: false
    labels:
      env: test
      role: test-kafka

  - name: kafka-inventory
    command: inventory
    arguments:
      default_jmx_user: jmx
      default_jmx_password: ************
      autodiscover_strategy: bootstrap
      bootstrap_broker_host: localhost
      bootstrap_broker_kafka_port: 9093
      bootstrap_broker_kafka_protocol: SSL
      bootstrap_broker_jmx_port: 9000
      tls_insecure_skip_verify: true
      kafka_version: 2.5.0
      topic_mode: All
    labels:
      env: test
      role: test-kafka
```

The agent itself doesn't throw any error messages around this that I can find, even with verbose: 1 enabled. So not sure how to debug deeper. Open to suggestions though.
